---
 - name: Playbook 1 provisoning test
   hosts: junos
   connection: local
   gather_facts: no
 
   tasks:
   - name: Retrieve information from devices running Junos
     hosts: junos
   - raw: |
     configure
     set protocols lldp interface all
     commit and-quit
