---
device:
   host_name: leaf03
   asn: 109

loopback:
 - name: loopback0
   ip: 10.20.3.1

link:
 - interface: "ge-0/0/1"
   name: to spine01
   ip: 172.16.0.1
   subnet: "31"
   neighbor: spine01
 - interface: "ge-0/0/2"
   name: to spine02
   ip: 172.16.0.7
   subnet: "31"
   neighbor: spine02
 - interface: "ge-0/0/3"
   name: to leaf04
   ip: 172.16.0.10
   subnet: "31"
   neighbor: leaf04
       
neighbor:
   leaf04:
     asn: 110
     peer_ip: 172.16.0.11
   spine02:
     asn: 105
     peer_ip: 172.16.0.6
   spine01:
     asn: 104
     peer_ip: 172.16.0.0
     