---
device:
   host_name: leaf03
   asn: 109
    
loopback:
   0:
     name: loopback0
     ip: 10.20.3.1

link:
   0:
     interface: "ge-0/0/1"
     name: to spine01
     ip: 172.16.0.1
     subnet: "31"
     neighbor:
       asn: 104
       peer_ip: 172.16.0.0
   1:
     interface: "ge-0/0/2"
     name: to spine02
     ip: 172.16.0.7
     subnet: "31"
     neighbor:
       asn: 105
       peer_ip: 172.16.0.6
   2:
     interface: "ge-0/0/3"
     name: to leaf04
     ip: 172.16.0.10
     subnet: "31"
     neighbor:
       asn: 110
       peer_ip: 172.16.0.11