---
device:
   host_name: leaf04
   asn: 110
    
loopback:
 - name: loopback0
   ip: 10.20.4.1

link:
 - interface: "ge-0/0/1"
   name: to spine01
   ip: 172.16.0.3
   subnet: "31"
   neighbor: spine01
 - interface: "ge-0/0/2"
   name: to spine02
   ip: 172.16.0.9
   subnet: "31"
   neighbor: spine02
 - interface: "ge-0/0/3"
   name: to leaf03
   ip: 172.16.0.11
   subnet: "31"
   neighbor: leaf03

neighbor:
   leaf03:
     asn: 109
     peer_ip: 172.16.0.10
   spine02:
     asn: 105
     peer_ip: 172.16.0.6
   spine01:
     asn: 104
     peer_ip: 172.16.0.0