---
device:
   host_name: spine02
   asn: 105
    
loopback:
   0:
     name: loopback0
     ip: 10.20.2.1

link:
   0:
     interface: "ge-0/0/1"
     name: to leaf03
     ip: 172.16.0.6
     subnet: "31"
     neighbor:
       asn: 109
       peer_ip: 172.16.0.7
   1:
     interface: "ge-0/0/2"
     name: to leaf04
     ip: 172.16.0.8
     subnet: "31"
     neighbor:
       asn: 110
       peer_ip: 172.16.0.9
   2:
     interface: "ge-0/0/3"
     name: to spine01
     ip: 172.16.0.5
     subnet: "31"
     neighbor:
       asn: 104
       peer_ip: 172.16.0.4