---
device:
   host_name: spine02
   asn: 105
    
loopback:
 - name: loopback0
   ip: 10.20.2.1

link:
 - interface: "ge-0/0/1"
   name: to leaf03
   ip: 172.16.0.6
   subnet: "31"
   neighbor: leaf03
 - interface: "ge-0/0/2"
   name: to leaf04
   ip: 172.16.0.8
   subnet: "31"
   neighbor: leaf04
 - interface: "ge-0/0/3"
   name: to spine01
   ip: 172.16.0.5
   subnet: "31"
   neighbor: spine01
    
neighbor:
   spine01:
     asn: 104
     peer_ip: 172.16.0.4
   leaf03:
     asn: 109
     peer_ip: 172.16.0.7
   leaf04:
     asn: 110
     peer_ip: 172.16.0.9  